import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.js'],
    css: false,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary', 'html'],
      // The 90% gate is enforced against the unit-tested core. As suites are
      // added for more of the app, widen `include` to bring them under the gate.
      include: [
        'src/server/api.js',
        'src/lib/deckOrder.js',
        'src/lib/deckUtils.js',
        'src/lib/elements.js',
        'src/lib/llmClient.js',
        'src/lib/decksApi.js',
        'src/lib/chartSpec.js',
        'src/lib/roadmapSpec.js',
        'src/lib/riskSpec.js',
        'src/lib/templateDeck.js',
        'src/lib/slideFactories.js',
        'src/lib/laser.js',
        'src/lib/slideEdit.js',
        'src/lib/align.js',
        'src/lib/slideFmt.js',
        'src/lib/color.js',
        'src/lib/domEvents.js',
        'src/lib/shapes.js',
        'src/lib/imageFile.js',
        'src/hooks/useDeckSync.js',
        'src/hooks/useReorderDrag.js',
        'src/hooks/useToasts.js',
        'src/hooks/useDeckHistory.js',
        'src/data/deck.js',
        'src/components/editor/CanvasSlide.jsx',
        'src/components/editor/FormatToolbar.jsx',
        'src/components/editor/ThumbsPane.jsx',
        'src/components/ui/EditableText.jsx',
        'src/components/ui/Toaster.jsx',
        'src/components/slides/SlideRenderer.jsx',
        'src/components/editor/inspector/DataPanel.jsx',
        'src/components/editor/inspector/DesignPanel.jsx',
        'src/components/editor/inspector/PropsPanel.jsx',
        'src/components/editor/inspector/InspectorBody.jsx',
        'src/components/editor/inspector/NumberCell.jsx',
        'src/components/editor/inspector/ChartDataEditor.jsx',
        'src/components/editor/inspector/RoadmapLanesEditor.jsx',
        'src/components/editor/inspector/ListItemsEditor.jsx',
        'src/components/editor/inspector/TableDataEditor.jsx',
        'src/components/modals/ExportModal.jsx',
        'src/components/views/SorterView.jsx',
        'src/components/views/SettingsView.jsx',
        'src/components/sorter/SorterGrid.jsx',
        'src/components/sorter/SorterToolbar.jsx',
        'src/components/presenter/LaserPointer.jsx',
        'src/components/presenter/LaserLayer.jsx',
        'src/components/presenter/PresenterControls.jsx',
      ],
      thresholds: {
        lines: 90,
        functions: 90,
        branches: 90,
        statements: 90,
      },
    },
  },
});
